POST http://localhost:3000 HTTP/1.1
content-type: application/json

{
    "title": "Sample Post",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT",
    "author": "Joe Thompson",
    "body": "This is a test blog post."
}

###

GET http://localhost:3000 HTTP/1.1

###

GET http://localhost:3000/latest HTTP/1.1

###

GET http://localhost:3000/648b3c6f609ff8be4131696a HTTP/1.1

###

GET http://localhost:3000/648b3c6f609ff8be4131696f HTTP/1.1

###

DELETE http://localhost:3000/648b3c6f609ff8be4131696a HTTP/1.1

###

PATCH http://localhost:3000/648c8069d3914fdbab08a470 HTTP/1.1
content-type: application/json

{
    "title": "Edited Post",
    "author": "jthompson"
}